# Generated by Django 5.0.1 on 2024-03-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_stars', models.IntegerField(choices=[(1, 'worst'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.musician')),
            ],
        ),
    ]
